# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import tabla.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[tabla.models.validar_cedula])),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=2, null=True)),
                ('fecha_de_nacimiento', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('elm_id', models.AutoField(primary_key=True, serialize=False)),
                ('elm_fila', models.CharField(max_length=5, verbose_name='Fila')),
                ('elm_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('elm_simbolo', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('elm_densidad', models.CharField(max_length=10, verbose_name='Densidad')),
                ('elm_electronegatividad', models.CharField(max_length=10, verbose_name='Electronegatividad')),
                ('elm_valencia', models.CharField(max_length=10, verbose_name='Valencia')),
                ('elm_peso_atomico', models.CharField(max_length=10, verbose_name='Peso atómico')),
                ('elm_numero_atomico', models.CharField(max_length=10, verbose_name='Numero atómico')),
                ('elm_configuracion_electronica', models.CharField(max_length=10, verbose_name='Configuración electrónica')),
                ('elm_descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('elm_estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8, verbose_name='Estado')),
            ],
        ),
    ]
